const customFieldsPersonsSummaryBase = [
  /*
  what's in this array ?
    // technical fields
        _id
        organisation
        createdAt
        updatedAt
    // fields métier that can't disappear or be changed
        outOfActiveList
        outOfActiveListDate
        user
        name
        birthdate
        alertness
        wanderingAt
        followedSince
        assignedTeams
        documents
        history
    // fields that can be partially or fully changed
        otherNames
        gender
        description
        phone
        outOfActiveListReasons

  */
  /* technical fields */
  {
    name: "_id",
    label: "",
    editable: "forbidden",
    encrypted: false,
    importable: false,
    filterable: false,
  },
  {
    name: "organisation",
    label: "",
    editable: "forbidden",
    encrypted: false,
    importable: false,
    filterable: false,
  },
  {
    name: "createdAt",
    type: "date",
    label: "",
    editable: "forbidden",
    encrypted: false,
    importable: false,
    filterable: false,
  },
  {
    name: "updatedAt",
    type: "date",
    label: "",
    editable: "forbidden",
    encrypted: false,
    importable: false,
    filterable: false,
  },
  /* fields métier that can't disappear or be changed */
  {
    name: "outOfActiveList",
    type: "yes-no",
    label: "Sortie de file active",
    editable: "forbidden",
    encrypted: true,
    importable: false,
    options: ["Oui", "Non"],
    filterable: true,
  },
  {
    name: "outOfActiveListDate",
    type: "date",
    label: "",
    editable: "forbidden",
    encrypted: true,
    importable: false,
    filterable: false,
  },
  {
    name: "user",
    type: "text",
    label: "",
    editable: "forbidden",
    encrypted: true,
    importable: false,
    filterable: false,
  },
  {
    name: "name",
    type: "text",
    label: "Nom prénom ou Pseudonyme",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "birthdate",
    type: "date",
    label: "Date de naissance",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "alertness",
    type: "boolean",
    label: "Personne très vulnérable",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "wanderingAt",
    type: "date",
    label: "En rue depuis le",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "followedSince",
    type: "date",
    label: "Suivi(e) depuis le / Créé(e) le",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "assignedTeams",
    type: "multi-choice",
    label: "Équipes en charge",
    editable: "forbidden",
    encrypted: true,
    importable: true,
    filterable: false,
  },
  {
    name: "documents",
    type: "files",
    label: "Documents",
    editable: "forbidden",
    encrypted: true,
    importable: false,
    filterable: false,
  },
  {
    name: "history",
    type: "history",
    label: "Historique",
    editable: "forbidden",
    encrypted: true,
    importable: false,
    filterable: false,
  },
  /* fields that can be partially or fully changed */
  {
    name: "otherNames",
    type: "text",
    label: "Autres pseudos",
    editable: "all",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "gender",
    type: "enum",
    label: "Genre",
    editable: "options",
    encrypted: true,
    importable: true,
    options: ["Aucun", "Homme", "Femme", "Homme transgenre", "Femme transgenre", "Non binaire", "Autre"],
    filterable: true,
  },
  {
    name: "description",
    type: "textarea",
    label: "Description",
    editable: "all",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "phone",
    type: "text",
    label: "Téléphone",
    editable: "all",
    encrypted: true,
    importable: true,
    filterable: true,
  },
  {
    name: "outOfActiveListReasons",
    type: "multi-choice",
    label: "Motifs de sortie de file active",
    options: [
      "Relai vers autre structure",
      "Hébergée",
      "Décès",
      "Incarcération",
      "Départ vers autre région",
      "Perdu de vue",
      "Hospitalisation",
      "Reconduite à la frontière",
      "Autre",
    ],
    showInStats: true,
    enabled: true,
    editable: "options",
  },
];

const customFieldsPersonsSocialBase = [
  {
    name: "personalSituation",
    type: "enum",
    label: "Situation personnelle",
    encrypted: true,
    importable: true,
    options: ["Aucune", "Homme isolé", "Femme isolée", "En couple", "Famille", "Famille monoparentale", "Mineur", "Autre"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "structureSocial",
    type: "text",
    label: "Structure de suivi social",
    encrypted: true,
    importable: true,
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "hasAnimal",
    type: "yes-no",
    label: "Avec animaux",
    encrypted: true,
    importable: true,
    options: ["Oui", "Non"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "address",
    type: "yes-no",
    label: "Hébergement",
    encrypted: true,
    importable: true,
    options: ["Oui", "Non"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "addressDetail",
    type: "enum",
    label: "Type d'hébergement",
    encrypted: true,
    options: [
      "Logement",
      "Hébergement association",
      "Chez un tiers",
      "Mise à l'abri",
      "Logement accompagné",
      "Urgence",
      "Insertion",
      "Hôtel",
      "Autre",
    ],
    importable: true,
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "nationalitySituation",
    type: "enum",
    label: "Nationalité",
    encrypted: true,
    importable: true,
    options: ["Hors UE", "UE", "Française", "Apatride"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "employment",
    type: "enum",
    label: "Emploi",
    encrypted: true,
    importable: true,
    options: ["DPH", "CDD", "CDDI", "CDI", "Interim", "Bénévolat", "Sans activité", "Étudiant", "Non déclaré", "Autre"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "resources",
    type: "multi-choice",
    label: "Ressources",
    encrypted: true,
    importable: true,
    options: [
      "SANS",
      "ARE",
      "RSA",
      "AAH",
      "ADA",
      "ATA",
      "Retraite",
      "Salaire",
      "Allocation Chômage",
      "Indemnités journalières",
      "Mendicité",
      "Aide financière CCAS",
      "Revenus de Formations",
      "Pension d'invalidité",
      "Contrat d'engagement jeune",
      "Contrat jeune majeur",
      "Autre",
    ],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "reasons",
    type: "multi-choice",
    label: "Motif de la situation en rue",
    encrypted: true,
    importable: true,
    options: [
      "Sortie d'hébergement",
      "Expulsion de logement/hébergement",
      "Départ du pays d'origine",
      "Départ de région",
      "Rupture familiale",
      "Perte d'emploi",
      "Sortie d'hospitalisation",
      "Problème de santé",
      "Sortie d'ASE",
      "Sortie de détention",
      "Rupture de soins",
      "Autre",
    ],
    filterable: true,
    enabled: true,
    editable: "all",
  },
];

const customFieldsPersonsMedicalBase = [
  {
    name: "healthInsurances",
    type: "multi-choice",
    label: "Couverture(s) médicale(s)",
    encrypted: true,
    importable: true,
    options: ["Aucune", "Régime Général", "PUMa", "AME", "CSS", "Autre"],
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "structureMedical",
    type: "text",
    label: "Structure de suivi médical",
    encrypted: true,
    importable: true,
    filterable: true,
    enabled: true,
    editable: "all",
  },
  {
    name: "consumptions",
    label: "Consommations",
    type: "multi-choice",
    options: [
      "Alcool",
      "Amphétamine/MDMA/Ecstasy",
      "Benzodiazépines",
      "Buprénorphine/Subutex",
      "Cocaïne",
      "Crack",
      "Cannabis",
      "Héroïne",
      "Lyrica",
      "Méthadone",
      "Moscantin/Skénan",
      "Tabac",
      "Tramadol",
    ],
    enabled: true,
    editable: "all",
    required: false,
    showInStats: true,
  },
  {
    name: "vulnerabilities",
    label: "Vulnérabilités",
    type: "multi-choice",
    options: ["Pathologie chronique", "Psychologique", "Injecteur", "Handicap"],
    enabled: true,
    editable: "all",
    required: false,
    showInStats: true,
  },
  {
    name: "caseHistoryTypes",
    label: "Catégorie d'antécédents",
    type: "multi-choice",
    options: [
      "Psychiatrie",
      "Neurologie",
      "Dermatologie",
      "Pulmonaire",
      "Gastro-enterologie",
      "Rhumatologie",
      "Cardio-vasculaire",
      "Ophtalmologie",
      "ORL",
      "Dentaire",
      "Traumatologie",
      "Endocrinologie",
      "Uro-gynéco",
      "Cancer",
      "Addiction alcool",
      "Addiction autres",
      "Hospitalisation",
    ],
    enabled: true,
    editable: "all",
    required: false,
    showInStats: true,
  },
  {
    name: "caseHistoryDescription",
    label: "Informations complémentaires (antécédents)",
    type: "textarea",
    options: null,
    enabled: true,
    editable: "all",
    required: false,
    showInStats: true,
  },
];

const defaultFieldsPersons = [
  { name: "Résumé", fields: customFieldsPersonsSummaryBase },
  { name: "Informations sociales", fields: customFieldsPersonsSocialBase },
  { name: "Informations médicales", fields: customFieldsPersonsMedicalBase },
];

module.exports = {
  customFieldsPersonsSummaryBase,
  customFieldsPersonsSocialBase,
  customFieldsPersonsMedicalBase,
  defaultFieldsPersons,
};
