app-api:
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: api
    - secretRef:
        name: azure-mano-volume
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"

app-www:
  host: "mano-app-preprod.dev.fabrique.social.gouv.fr"
