version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 35
  return-statements:
    config:
      threshold: 15
  method-complexity:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 70
plugins:
  duplication:
    enabled: false
