plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
      - files:
        - api/package.json
        - website/package.json
        - dashboard/package.json
        from: "\"version\": \".*\""
        to: "\"version\": \"${nextRelease.version}\""
        results:
        - file: api/package.json
          hasChanged: true
          numMatches: 1
          numReplacements: 1
        - file: website/package.json
          hasChanged: true
          numMatches: 1
          numReplacements: 1
        - file: dashboard/package.json
          hasChanged: true
          numMatches: 1
          numReplacements: 1
        countMatches: true
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - README.md
        - api/package.json
        - website/package.json
        - dashboard/package.json
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
