www:
  host: "mano-app.fabrique.social.gouv.fr"
  certSecretName: www-crt

api:
  host: "mano.fabrique.social.gouv.fr"
  certSecretName: api-crt
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: api
    - configMapRef:
        name: api
    - secretRef:
        name: azure-mano-volume
    - secretRef:
        name: pg-app

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 3Gi

pg-metabase:
  ~chart: pg

dashboard:
  host: "dashboard-mano.fabrique.social.gouv.fr"
  certSecretName: dashboard-crt

metabase:
  enabled: true
  ingress:
    enabled: false
  env:
    - name: MB_DB_CONNECTION_URI
      value: "postgres://$(PGHOST):5432/$(PGDATABASE)?user=$(PGUSER)&password=$(PGPASSWORD)&ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory"
  envFrom:
    - configMapRef:
        name: metabase-configmap
    - secretRef:
        name: metabase-db-user
    - secretRef:
        name: pg-metabase-app

oauth2-proxy:
  host: "metabase-mano.fabrique.social.gouv.fr"
  certSecretName: oauth2-proxy-crt
  enabled: true
  upstream: http://metabase
  envFrom:
    - configMapRef:
        name: oauth2-proxy-configmap
    - secretRef:
        name: oauth2-proxy-sealed-secret
  additionalArgs:
    - --skip-auth-route
    - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*

jobs:
  ~chart: jobs
  runs:
    build-dashboard:
      with:
        secrets:
          sentry_auth_token:
            secretName: dashboard
            secretKey: SENTRY_AUTH_TOKEN
          react_app_org_duplicated_1_id:
            secretName: dashboard
            secretKey: REACT_APP_ORG_DUPLICATED_1_ID
          react_app_org_duplicated_1_name:
            secretName: dashboard
            secretKey: REACT_APP_ORG_DUPLICATED_1_NAME
          react_app_org_duplicated_2_id:
            secretName: dashboard
            secretKey: REACT_APP_ORG_DUPLICATED_2_ID
          react_app_org_duplicated_2_name:
            secretName: dashboard
            secretKey: REACT_APP_ORG_DUPLICATED_2_NAME
          react_app_org_id_for_truplication:
            secretName: dashboard
            secretKey: REACT_APP_ORG_ID_FOR_TRUPLICATION
