www:
  host: "mano-app.fabrique.social.gouv.fr"
  certSecretName: www-crt

api:
  host: "mano.fabrique.social.gouv.fr"
  certSecretName: api-crt
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: api
    - configMapRef:
        name: api
    - secretRef:
        name: azure-mano-volume
    - secretRef:
        name: pg-app

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 3Gi

dashboard:
  host: "dashboard-mano.fabrique.social.gouv.fr"
  certSecretName: dashboard-crt

metabase:
  enabled: true
  ingress:
    enabled: false
  envFrom:
    - configMapRef:
        name: metabase-configmap
    - secretRef:
        name: metabase-db-user

oauth2-proxy:
  host: "metabase-mano.fabrique.social.gouv.fr"
  certSecretName: oauth2-proxy-crt
  enabled: true
  upstream: http://metabase
  envFrom:
    - configMapRef:
        name: oauth2-proxy-configmap
    - secretRef:
        name: oauth2-proxy-sealed-secret
  additionalArgs:
    - --skip-auth-route
    - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*

jobs:
  ~chart: jobs
  runs:
    build-dashboard:
      with:
        secrets:
          sentry_auth_token:
            secretName: dashboard
            secretKey: SENTRY_AUTH_TOKEN
          react_app_org_id_for_migration:
            secretName: dashboard
            secretKey: REACT_APP_ORG_ID_FOR_MIGRATION
          react_app_team_1:
            secretName: dashboard
            secretKey: REACT_APP_TEAM_1
          react_app_team_2:
            secretName: dashboard
            secretKey: REACT_APP_TEAM_2
