import { test, expect } from "@playwright/test";
import { nanoid } from "nanoid";
import { populate } from "./scripts/populate-db";

test.beforeAll(async () => {
  await populate();
});

test("test", async ({ page }) => {
  const premier = "premier-" + nanoid();
  const deuxieme = "deuxieme-" + nanoid();
  const monAction = "monAction-" + nanoid();
  const testTerritoire = "testTerritoire-" + nanoid();

  await page.goto("http://localhost:8090/auth");
  await page.getByPlaceholder("Cliquez ici pour entrer votre email").fill("admin1@example.org");
  await page.getByPlaceholder("Cliquez ici pour entrer votre mot de passe").fill("secret");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByLabel("Clé de chiffrement d'organisation").fill("plouf");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByRole("button", { name: "Créer une nouvelle personne" }).click();
  await page.getByLabel("Nom").click();
  await page.getByLabel("Nom").fill(premier);
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByRole("button", { name: "Créer une nouvelle personne" }).click();
  await page.getByLabel("Nom").click();
  await page.getByLabel("Nom").fill(deuxieme);
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByRole("button", { name: "Personnes suivies" }).click();
  await page
    .getByLabel(
      'Activer la possibilité d\'ajouter des liens familiaux entre personnes. Un onglet "Famille" sera rajouté dans les personnes, et vous pourrez créer des actions, des commentaires et des documents visibles pour toute la famille.'
    )
    .check();
  await page.getByRole("button", { name: "Mettre à jour" }).first().click();
  await page.getByText("Mise à jour !").click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByText(premier).click();
  await page.getByRole("button", { name: "Ajouter un commentaire" }).click();
  await page.getByRole("textbox", { name: "Commentaire" }).fill("commentaire test");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Commentaire enregistré").click();
  await page.getByRole("button", { name: "Ajouter une action" }).click();
  await page.getByLabel("Nom de l'action").fill(monAction);
  await page.getByLabel("Commentaire (optionnel)").click();
  await page.getByLabel("Commentaire (optionnel)").fill("Avec un commentaire");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("button", { name: "Éditer les informations sociales" }).click();
  await page.getByLabel("Structure de suivi social").click();
  await page.getByLabel("Structure de suivi social").fill("SUIVI HOP");
  await page.getByText("Informations médicales+").click();
  await page.getByLabel("Structure de suivi médical").click();
  await page.getByLabel("Structure de suivi médical").fill("MDEIDAL");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Mis à jour !").click();
  await page.getByRole("button", { name: "Ajouter un passage" }).click();
  await page.getByLabel("Commentaire").click();
  await page.getByLabel("Commentaire").fill("le passage");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Passage enregistré").click();
  await page.getByRole("button", { name: "Rencontres (0)" }).click();
  await page.getByRole("button", { name: "Ajouter une rencontre" }).click();
  await page.getByLabel("Commentaire").click();
  await page.getByLabel("Commentaire").fill("La rencontre");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Rencontre enregistrée").click();
  await page.getByRole("button", { name: "Dossier Médical" }).click();
  await page.getByRole("button", { name: "🩺 Ajouter une consultation" }).click();
  await page.getByLabel("Nom (facultatif)").fill("La consultation");
  await page.locator(".consultation-modal-type__input-container").click();
  await page.locator("#react-select-type-option-0").click();
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByRole("button", { name: "💊 Ajouter un traitement" }).click();
  await page.getByPlaceholder("Amoxicilline").click();
  await page.getByPlaceholder("Amoxicilline").fill("le traitement");
  await page.getByPlaceholder("1mg").click();
  await page.getByPlaceholder("1mg").fill("1mg");
  await page.getByPlaceholder("1 fois par jour").click();
  await page.getByPlaceholder("1 fois par jour").fill("12 fois");
  await page.getByPlaceholder("Angine").click();
  await page.getByPlaceholder("Angine").fill("Rhume");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Traitement créé !").click();
  await page.getByLabel("Numéro de sécurité sociale").click();
  await page.getByLabel("Numéro de sécurité sociale").fill("12345");
  await page
    .locator('[data-test-id="' + premier + 'Dossier Médical"] div')
    .filter({ hasText: "Numéro de sécurité socialeLoading...Mettre à jour" })
    .getByRole("button", { name: "Mettre à jour" })
    .click();
  await page.getByText("Mise à jour effectuée !").click();
  await page.getByRole("button", { name: "Lieux fréquentés (0)" }).click();
  await page.getByRole("button", { name: "Fermer" }).click();
  await page.getByRole("button", { name: "Ajouter un lieu" }).click();
  await page.getByRole("combobox", { name: "Lieu" }).fill("test lieu");
  await page.getByText('Créer "test lieu"').click();
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Le lieu a été ajouté").click();
  await page.getByRole("button", { name: "Liens familiaux (0)" }).click();
  await page.getByRole("button", { name: "Ajouter un lien" }).click();
  await page.locator(".person-family-relation__input-container").click();
  await page.locator("#person-family-relation").fill("deu");
  await page.locator("#react-select-personId-option-0").click();
  await page.getByPlaceholder("Père/fille, mère/fils...").fill("père");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Le lien familial a été ajouté").click();
  await page.getByRole("link", { name: "Territoires" }).click();
  await page.getByRole("button", { name: "Créer un nouveau territoire" }).click();
  await page.getByLabel("Nom").click();
  await page.getByLabel("Nom").fill(testTerritoire);
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("button", { name: "Nouvelle observation" }).click();
  await page.getByLabel("Commentaire").click();
  await page.getByLabel("Commentaire").fill("Un commentaire");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("link", { name: "Structures" }).click();
  await page.getByRole("button", { name: "Créer une nouvelle structure" }).click();
  await page.getByLabel("Nom").fill("Une structure");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByText("Structure créée !").click();
  await page.getByRole("link", { name: "Comptes rendus" }).click();
  await page.getByRole("button", { name: "2023-02-10" }).click();
  await page.locator(".report-select-collaboration__input-container").click();
  await page.locator("#react-select-collaborations-option-0").click();
  await page.getByRole("button", { name: "Mettre à jour" }).click();
  await page.getByText("Mis à jour !").click();

  await page.getByRole("button", { name: "Ajouter une description" }).click();
  await page.getByRole("textbox", { name: "Description Description" }).fill("La description");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByRole("navigation", { name: "Navigation dans les catégories du compte-rendu" }).getByText("Accueil").click();
  await page.locator('[id="Café-add"]').click();
  await page.locator("#Douche-add").click();
  await page.locator("#Douche-add").click();
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByRole("link", { name: "Agenda" }).click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByRole("button", { name: "Chiffrement" }).click();
  await page.getByRole("button", { name: "Changer la clé de chiffrement" }).click();
  await page.locator("#encryptionKey").click();
  await page.locator("#encryptionKey").fill("plaf");
  await page.getByLabel("Confirmez la clé de chiffrement").click();
  await page.getByLabel("Confirmez la clé de chiffrement").fill("plaf");
  await page.locator('[data-test-id="encryption-modal"]').getByRole("button", { name: "Changer la clé de chiffrement" }).click();
  await page.getByText("Données chiffrées ! Veuillez noter la clé puis vous reconnecter").click();
  await page.locator('[data-test-id="encryption-modal"]').getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "User Admin Test - 1" }).click();
  await page.getByRole("menuitem", { name: "Se déconnecter" }).first().click();
  await page.getByPlaceholder("Cliquez ici pour entrer votre email").fill("admin1@example.org");
  await page.getByPlaceholder("Cliquez ici pour entrer votre mot de passe").fill("secret");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByLabel("Clé de chiffrement d'organisation").fill("plaf");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByRole("link", { name: "Agenda" }).click();
  await page.getByText("La consultation").click();
  await page.getByRole("button", { name: "Annuler" }).click();
  await page.getByRole("cell", { name: "le traitement Rhume" }).click();
  await page.getByRole("button", { name: "Close" }).click();
  await page.getByRole("cell", { name: "La consultation Médicale" }).click();
  await page.getByRole("button", { name: "Annuler" }).click();
  await page.getByLabel("Structure de suivi médical").click();
  await page.getByLabel("Numéro de sécurité sociale").click();
  await page.getByRole("button", { name: "Lieux fréquentés (1)" }).click();
  await page.locator('[data-test-id="test lieu"]').click();
  await page.getByRole("button", { name: "Liens familiaux (1)" }).click();
  await page.getByRole("cell", { name: premier + " et " + deuxieme }).click();
  await page.getByRole("button", { name: "Résumé" }).click();
  await page.getByText("SUIVI HOP").click();
  await page.getByText("MDEIDAL").click();
  await page.getByText("le passage").click();
  await page.getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "Rencontres (1)" }).click();
  await page.getByText("La rencontre").click();
  await page.getByRole("button", { name: "Close" }).click();
  await page.getByRole("link", { name: "Territoires" }).click();
  await page.getByText(testTerritoire).click();
  await page.getByText("Un commentaire").click();
  await page.getByRole("button", { name: "Close" }).click();
  await page.getByRole("link", { name: "Agenda" }).click();
  await page.getByText(monAction).click();
  await page.getByText("Avec un commentaire").click();
  await page.getByRole("button", { name: "Annuler" }).click();
  await page.getByRole("link", { name: "Comptes rendus" }).click();
  await page.getByRole("button", { name: "2023-02-10" }).click();
  await page.getByText("La description").click();
  await page.getByText("Ma première collab").click();
  await page.getByText("Actions créées (1)").click();
  await page.getByText("Commentaires (2)").click();
  await page.getByText("Passages (1)").click();
  await page.getByText("Rencontres (1)").click();
  await page.getByText("Observations (1)").click();
  await page.getByText("Personnes créées (2)").click();
  await page.getByText("Consultations créées (1)").click();
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByRole("button", { name: "Chiffrement" }).click();
  await page.getByRole("button", { name: "Changer la clé de chiffrement" }).click();
  await page.locator("#encryptionKey").click();
  await page.locator("#encryptionKey").fill("plouf");
  await page.getByLabel("Confirmez la clé de chiffrement").click();
  await page.getByLabel("Confirmez la clé de chiffrement").fill("plouf");
  await page.locator('[data-test-id="encryption-modal"]').getByRole("button", { name: "Changer la clé de chiffrement" }).click();
  await page.getByText("Données chiffrées ! Veuillez noter la clé puis vous reconnecter").click();
  await page.locator('[data-test-id="encryption-modal"]').getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "User Admin Test - 1" }).click();
  await page.getByRole("menuitem", { name: "Se déconnecter" }).first().click();
  await page.getByPlaceholder("Cliquez ici pour entrer votre email").click();
  await page.getByPlaceholder("Cliquez ici pour entrer votre email").fill("admin1@example.org");
  await page.getByPlaceholder("Cliquez ici pour entrer votre mot de passe").click();
  await page.getByPlaceholder("Cliquez ici pour entrer votre mot de passe").fill("secret");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByLabel("Clé de chiffrement d'organisation").fill("plouf");
  await page.getByRole("button", { name: "Se connecter" }).click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByText(deuxieme).click();
});
