import { test, expect } from "@playwright/test";
import { populate } from "./scripts/populate-db";
import { loginWith } from "./utils";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc";
import "dayjs/locale/fr";

dayjs.extend(utc);
dayjs.locale("fr");
test.beforeAll(async () => {
  await populate();
});

test("Création de rencontres dans les observations de territoire", async ({ page }) => {
  const date = dayjs();
  await loginWith(page, "admin1@example.org");
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByRole("button", { name: "Passages/rencontres" }).click();
  await page.getByRole("link", { name: "Personnes suivies" }).click();
  await page.getByRole("button", { name: "Créer une personne" }).click();

  await page.getByLabel("Nom").fill("raph");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByText("Retour").click();
  await page.getByRole("button", { name: "Créer une personne" }).click();
  await page.getByLabel("Nom").fill("arnaud");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("link", { name: "Territoires" }).click();
  await page.getByRole("button", { name: "Créer un territoire" }).click();
  await page.getByLabel("Nom").click();
  await page.getByLabel("Nom").fill("stalingrad");
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByRole("button", { name: "Nouvelle observation" }).click();
  await page.getByLabel("Nombre de personnes non connues hommes rencontrées").fill("100");
  await page.getByRole("button", { name: "Rencontres" }).click();
  await page.locator("#person-select-and-create-reception").click();
  await page.getByText("raph", { exact: true }).click();
  await page.locator("#person-select-and-create-reception").click();
  await page.getByText("arnaud", { exact: true }).click();
  await page.getByRole("button", { name: "+ Rencontre" }).click();
  await page.getByRole("textbox", { name: "Commentaire" }).fill("rencontre des deux");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByRole("row", { name: "raph" }).getByRole("button").click();
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Création réussie !").click();
  await page.getByText("Les rencontres ont également été sauvegardées").click();
  await page.getByRole("cell", { name: date.format("MMMM YYYY") }).click();
  await page.getByRole("button", { name: "Informations" }).click();
  await page.getByRole("button", { name: "Rencontres (1)" }).click();
  await page.getByRole("button", { name: "+ Rencontre" }).click();
  await page.locator(".person__indicator").click();
  await page.getByText("raph", { exact: true }).click();
  await page.getByRole("textbox", { name: "Commentaire" }).fill("aussi");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await page.getByRole("button", { name: "Sauvegarder" }).click();
  await page.getByText("Observation mise à jour").click();
  await page.getByText("Les rencontres ont également été sauvegardées").click();
  await page.getByRole("link", { name: "Comptes rendus" }).click();
  await page.getByText("1observation").click();
  await page.getByText("2personnes créée").click();
  await page.getByText("2rencontresRencontres (2)").click();
  await page.getByRole("button", { name: "Passer les rencontres en" }).click();
  await page.locator('[data-test-id="modal"]').getByRole("cell", { name: "raph" }).click();
  await page.getByLabel("Close").click();
  await page.locator('[data-test-id="modal"]').getByText("arnaud").click();
});
