app-www:
  needs: [app-api]

app-api:
  needs: [seed]
  volumes:
    - name: files
      emptyDir: {}
  volumeMounts:
    - mountPath: /mnt/files
      name: files

jobs:
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db@v1
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    - name: seed
      needs: [db]
      use: SocialGouv/kube-workflow/jobs/seed-db@v1
      with:
        seedPath: api/mocked-db.sql
