app-www:
  host: "mano-app-{{ .Values.global.host }}"
  containerPort: 8080
  enabled: true
  imagePackage: www

app-api:
  host: "mano-{{ .Values.global.host }}"
  enabled: true
  containerPort: 3000
  imagePackage: api
  probesPath: /healthz
  env:
    - name: STORAGE_DIRECTORY
      value: "/mnt/files"
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"

app-dashboard:
  host: "dashboard-mano-{{ .Values.global.host }}"
  enabled: true
  containerPort: 8080
  imagePackage: dashboard

metabase:
  enabled: false

oauth2-proxy:
  enabled: false
