projectName: mano
ciNamespace: ci-mano

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev, preprod]
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                mano-dev-backups-access-key:
                mano-prod-backups-access-key:
