www:
  ~chart: app
  ~needs: [build-www]
  host: "app-{{ .Values.global.host }}"
  containerPort: 8080
  enabled: true
  imagePackage: www
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self' https://*.gouv.fr; font-src 'self'; img-src 'self'; prefetch-src 'self' https://*.gouv.fr; script-src 'self' https://*.gouv.fr; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-XSS-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: nosniff";

api:
  ~chart: app
  ~needs: [build-api]
  host: "{{ .Values.global.host }}"
  enabled: true
  containerPort: 3000
  imagePackage: api
  probesPath: /healthz
  env:
    - name: STORAGE_DIRECTORY
      value: "/mnt/files"
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"

dashboard:
  ~chart: app
  ~needs: [build-dashboard]
  host: "dashboard-{{ .Values.global.host }}"
  enabled: true
  containerPort: 8080
  imagePackage: dashboard

metabase:
  ~chart: metabase
  enabled: false

oauth2-proxy:
  ~chart: oauth2-proxy
  enabled: false

jobs:
  ~chart: jobs
  runs:
    build-www:
      use: build
      with:
        imagePackage: www
        dockerfile: website/Dockerfile
        context: "."
    build-api:
      use: build
      with:
        imagePackage: api
        dockerfile: api/Dockerfile
        context: "."
    build-dashboard:
      use: build
      with:
        imagePackage: dashboard
        dockerfile: dashboard/Dockerfile
        context: "."
