name: Deploy on Main Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: website/yarn.lock
      # On vérifie si le dossier website a été modifié pour faire un build
      - name: Check for changes in website directory
        id: check_changes
        run: |
          echo "WEBSITE_CHANGED=false" >> $GITHUB_ENV
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'website/'; then
            echo "WEBSITE_CHANGED=true" >> $GITHUB_ENV
          fi
      # On build seulement si le dossier website a été modifié
      - name: Build wesite
        if: env.WEBSITE_CHANGED == 'true'
        env:
          NEXT_TELEMETRY_DISABLED: 1

        run: |
          cd website
          yarn
          yarn build
      # TODO pour plus tard, on pourrait deploy seulement le dossier qui a été modifié
      - name: Trigger deployment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"deploy-key":"'"$DEPLOY_KEY"'"}' https://preprod-api-mano.sesan.fr/api/deploy
