name: Deploy on Main Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"deploy-key":"'"$DEPLOY_KEY"'"}' https://preprod-api-mano.sesan.fr/api/deploy
