name: Review

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER WEBSITE IMAGE
  ##############################################################################
  register-website:
    name: Register website
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: mano/www
          dockerfile: website/Dockerfile
          dockercontext: .

  ##############################################################################
  ## BUILD AND REGISTER DASHBOARD IMAGE
  ##############################################################################
  register-dashboard:
    name: Register dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: mano/dashboard
          dockerfile: dashboard/Dockerfile
          dockercontext: .

  ##############################################################################
  ## BUILD AND REGISTER API IMAGE
  ##############################################################################
  register-api:
    name: Register api
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: mano/api
          dockerfile: api/Dockerfile
          dockercontext: .

  ##############################################################################
  ## DEPLOY ALL
  ##############################################################################
  deploy-all:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register-website, register-dashboard, register-api]
    steps:
      - uses: SocialGouv/kube-workflow@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
