name: Securised github secret getter

on:
  push:
    branches: ["**"]

concurrency:
  cancel-in-progress: true
  group: reveal-${{ github.ref }}

jobs:
  reveal:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: alessiodionisi/setup-age-action@v1.2.1
      - name: Reveal
        run: |
          echo ${{ secrets.KUBECONFIG }} > secret
          echo ${{ secrets.REVEAL_PUBKEY_B64 }} | base64 -d > alice.pub
          age -R alice.pub secret | base64
          rm secret